remote_theme: lorepirri/cayman-blog

title: Steve Halliwell's Blog
#description: Cayman Blog Theme is a clean, responsive blogging theme for Jekyll and Gitlab/GitHub Pages.

# social
twitter:
  username: _stevehalliwell

header_page_refs: ['contact']